{% set name = "sqlite-anyio" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 12a8b0ececaa63d70d5cc5f91edbd932fc1eca9da70ebce2b31d3a199767b3d3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - anyio >=4.0,<5.0

test:
  source_files:
    - tests
  imports:
    - sqlite_anyio
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - trio

about:
  home: https://github.com/davidbrochart/sqlite-anyio
  summary: Asynchronous client for SQLite using AnyIO
  license_file: LICENSE
  license: MIT
  license_family: MIT
  dev_url: https://github.com/davidbrochart/sqlite-anyio
  doc_url: https://github.com/davidbrochart/sqlite-anyio/blob/main/README.md

extra:
  recipe-maintainers:
    - davidbrochart
